name: Angular CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build the Angular app
        run: npm run build -- --configuration=production --base-href "/my-portfolio"

      - name: Upload production-ready files
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: dist/my_portfolio

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build files
        uses: actions/download-artifact@v4
        with:
          name: build-files
          path: dist/my_portfolio

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          publish_dir: ./dist/my_portfolio
