name: Deploy Angular App i.e. Portfolio to GitHub Pages

on:
  push:
    branches:
      - gh-pages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18" # Set the Node.js version you need

      - name: Install dependencies
        run: npm install

      - name: Build Angular project
        run: npm run build -- --output-path=docs --base-href=/my-portfolio/

      - name: Create .nojekyll file (to prevent Jekyll processing)
        run: touch docs/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          branch: gh-pages # The branch to deploy to (gh-pages)
          # folder: docs # The folder where the Angular build is placed
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
